- name: Update apt cache
  apt:
    update_cache: yes
  tags: sabnzbd

- name: Add SABnzbd PPA repository
  apt_repository:
    repo: ppa:jcfp/nobetas
    state: present
  tags: sabnzbd

- name: Add SABnzbd Addons PPA repository
  apt_repository:
    repo: ppa:jcfp/sab-addons
    state: present
  tags: sabnzbd

- name: Update apt cache after adding PPAs
  apt:
    update_cache: yes
  tags: sabnzbd

- name: Install SABnzbd and Par2-Turbo
  apt:
    name:
      - sabnzbdplus
      - par2-turbo
    state: present
  tags: sabnzbd

- name: Ensure .sabnzbd directory exists
  file:
    path: "/home/{{ sabnzbd_user }}/.sabnzbd"
    state: directory
    owner: "{{ sabnzbd_user }}"
    group: "{{ sabnzbd_user }}"
    mode: "0755"
  become: true
  tags: sabnzbd

- name: Download SABnzbd systemd service template
  get_url:
    url: https://raw.githubusercontent.com/sabnzbd/sabnzbd/master/linux/sabnzbd%40.service
    dest: "/etc/systemd/system/sabnzbd@.service"
    mode: "0644"
  become: true
  tags: sabnzbd

- name: Check SABnzbd installation path
  stat:
    path: "/opt/sabnzbd/SABnzbd.py"
  register: sabnzbd_script
  tags: sabnzbd

- name: Check PPA installation path
  stat:
    path: "/usr/bin/sabnzbdplus"
  register: sabnzbd_ppa
  tags: sabnzbd

- name: Update service file for PPA installation
  lineinfile:
    path: "/etc/systemd/system/sabnzbd@.service"
    regexp: "^ExecStart\\=/opt/sabnzbd/SABnzbd.py"
    line: "ExecStart=/usr/bin/sabnzbdplus --disable-file-log --logging 1 --browser 0"
  become: true
  when: not sabnzbd_script.stat.exists and sabnzbd_ppa.stat.exists
  tags: sabnzbd

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  become: true
  tags: sabnzbd

- name: Enable and start SABnzbd service using template
  systemd:
    name: "sabnzbd@{{ sabnzbd_user }}.service"
    enabled: true
    state: started
  become: true
  tags: sabnzbd

- name: Set sabnzbd service state
  service_facts:
  tags: sabnzbd

- name: Display service status
  debug:
    msg: "SABnzbd service status: {{ ansible_facts.services['sabnzbd@' + sabnzbd_user + '.service'].state }}"
  tags: sabnzbd
