- name: Update apt cache
  apt:
    update_cache: yes
  tags: sabnzbd

- name: Add SABnzbd PPA repository
  apt_repository:
    repo: ppa:jcfp/nobetas
    state: present
  tags: sabnzbd

- name: Update apt cache after adding PPA
  apt:
    update_cache: yes
  tags: sabnzbd

- name: Install SABnzbd
  apt:
    name: sabnzbdplus
    state: present
  tags: sabnzbd

- name: Configure SABnzbd service user
  lineinfile:
    path: /etc/default/sabnzbdplus
    regexp: "^USER="
    line: "USER={{ sabnzbd_user }}"
    state: present
  become: true
  tags: sabnzbd

- name: Configure SABnzbd to start on boot
  lineinfile:
    path: /etc/default/sabnzbdplus
    regexp: "^ENABLED="
    line: "ENABLED=1"
    state: present
  become: true
  tags: sabnzbd

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  become: true
  tags: sabnzbd

- name: Enable and start sabnzbdplus service
  systemd:
    name: sabnzbdplus
    enabled: true
    state: started
  become: true
  tags: sabnzbd
