- name: Update apt cache
  apt:
    update_cache: yes
  tags: sabnzbd

- name: Add SABnzbd PPA repository
  apt_repository:
    repo: ppa:jcfp/nobetas
    state: present
  tags: sabnzbd

- name: Update apt cache after adding PPA
  apt:
    update_cache: yes
  tags: sabnzbd

- name: Install SABnzbd
  apt:
    name: sabnzbdplus
    state: present
  tags: sabnzbd

- name: Enable and start sabnzbdplus service
  systemd:
    name: sabnzbdplus
    enabled: yes
    state: started
  tags: sabnzbd
