---
- name: Erstelle Reverse Proxy Eintrag über API Wrapper Bash Script
  hosts: localhost
  gather_facts: false
  vars:
    proxy_ip: "192.168.1.100"
    proxy_port: 8080
    domain: "example.com"
    script_path: "/root/npm/nginx_proxy_manager_cli.sh"
  tasks:
    - name: Führe Bash Skript aus, um den Proxy Host zu erstellen
      shell: "{{ script_path }} -d {{ domain }} -i {{ proxy_ip }} -p {{ proxy_port }}"
      register: script_output
    - name: Zeige die Ausgabe des Skripts an
      debug:
        var: script_output
