---
- name: Create a server in Hetzner Cloud
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create the "{{ SERVER_NAME }}" server
      hetzner.hcloud.hcloud_server:
        state: present
        name: "{{ SERVER_NAME }}" # Server name
        server_type: cax21 # Server type
        image: ubuntu-24.04 # Operating system image
        ssh_keys:
          - HetznerMediaProjekt # Hetzner SSH Key as an array
        private_networks:
          - Media-Central # Private network as an array
        api_token: "{{ HETZNER_CLOUD }}"
