---
- name: LXC-Container mit Ubuntu 24.10 auf Proxmox erstellen
  hosts: localhost
  gather_facts: true
  vars:
    # Proxmox API Einstellungen
    proxmox_api_host: "{{ PROXMOX_HOST }}"
    proxmox_user: "{{ PROXMOX_USER }}"
    proxmox_password: "{{ PROXMOX_PASSWORD }}"
    node: "{{ PROXMOX_NODE_NAME }}"
    vmid: 101 # Eine eindeutige ID für den Container

    # Container-Einstellungen
    hostname: "ubuntu-container"
    ostemplate: "local:vztmpl/ubuntu-24.10-standard_24.10-1_amd64.tar.gz" # Pfad zum Template
    storage: "local-lvm" # Speicherort auf dem Proxmox Server
    password: "{{ ROOT_PASSWORD }}" # Root-Passwort im Container
    cores: 2 # Anzahl der CPU-Kerne
    memory: 2048 # Arbeitsspeicher in MB
    swap: 512 # Swap in MB
    netif: '{"net0": "name=eth0,bridge=vmbr0,ip=dhcp,tag=10,type=veth"}' # Netzwerkkonfiguration

  tasks:
    - name: Erstelle LXC-Container
      community.general.proxmox:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        hostname: "{{ hostname }}"
        ostemplate: "{{ ostemplate }}"
        password: "{{ password }}"
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        swap: "{{ swap }}"
        netif: "{{ netif }}"
        storage: "{{ storage }}"
        ostype: "ubuntu"
        state: present
      delegate_to: localhost
