---
- name: Create a server in Hetzner Cloud
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create the "Media01" server
      hetzner.hcloud.hcloud_server:
        state: present
        name: Media01 # Server name
        server_type: CAX21 # Server type
        image: ubuntu-24.04 # Operating system image
        ssh_keys:
          - HetznerMediaProjekt # Hetzner SSH Key as an array
        networks:
          - Media-Central # Private network as an array
        api_token: "{{ HETZNER_CLOUD }}"
